### PR TITLE
Add validate method for echo verb

### PR DESCRIPTION
**Pull request by alex-seville**
The Flickr API has a couple validation endpoints, under flickr.test.  I think `test` is an ambiguous namespace and that validation is better suited.

I also pass a fixed parameter name and echo value in through this method, since exposing it to arbitrary parameter values doesn't serve a purpose.

I added a test, and also cleaned up a js-hint issue in the test.

Addresses: https://github.com/flickr/flickr/issues/1

### CODE REVIEW

**Comment by alex-seville** [comment]
Failing because it's dependent on https://github.com/flickr/flickr-api-swagger/pull/1

**Comment by jimwhimpey** [comment]
Need to bump the `flickr-api-swagger` dependency to 2.3.0 now that it's published.

**Comment by jimwhimpey** [comment]
Excellent, thanks!

**Comment by flrent** [comment]
👍

**Pull request merged**
